---
alias: Hall Hue Dimmer
id: 2c669db3-2e5a-4bb3-bfd9-e60c2fea2625
description: Used to toggle the light in the hall and motion sensor.
mode: queued
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:17:88:01:04:ac:85:50"
action:
  choose:
    # ON
    - conditions:
      - "{{ trigger.event.data.command == 'on_press' }}"
      sequence:
        - action: automation.turn_off
          entity_id: automation.light_hall
        - action: light.turn_on
          data:
            entity_id: light.flur
            transition: 3
            brightness_pct: 80
    # Step up
    - conditions:
      - "{{ trigger.event.data.args == [0, 30, 9] }}"
      sequence:
        - action: light.turn_on
          data:
            entity_id: light.flur
            brightness_step_pct: 10
    # Step down
    - conditions:
      - "{{ trigger.event.data.args == [1, 30, 9] }}"
      sequence:
        - action: light.turn_on
          data:
            entity_id: light.flur
            brightness_step_pct: -10
    # OFF
    - conditions:
      - "{{ trigger.event.data.command == 'off_press' }}"
      sequence:
        - action: automation.turn_on
          entity_id: automation.light_hall
        - delay: '00:00:15'
        - action: light.turn_off
          entity_id: light.flur
