---
alias: Light Hall Home
id: 9180ed16-c040-4ce2-ab8e-bdbb4a607ae1
description: Turn on the light in the hall when coming home.
mode: restart
trigger:
  - trigger: state
    entity_id: person.jannis
    to: "home"
  - trigger: state
    entity_id: person.hannah
    to: "home"
condition:
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"
action:
  - wait_for_trigger:
      - trigger: state
        entity_id: binary_sensor.contact_door
        to: 'on'
    timeout: '00:10:00'
    continue_on_timeout: false
  - action: light.turn_on
    data:
      entity_id: light.flur
      brightness_pct: 100