---
alias: Light Hall
id: c2df6567-a636-48a3-8c86-fec73b866634
description: Turn on the light in the hall when presence is detected or turn it off if there is no motion.
mode: queued
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - binary_sensor.presence_hall
      - input_boolean.motion_sensor
      - alarm_control_panel.ha_alarm
action:
  choose:
    # Motion detected
    - conditions:
        - condition: state
          entity_id: binary_sensor.presence_hall
          state: 'on'
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: disarmed
        - condition: state
          entity_id: input_boolean.motion_sensor
          state: 'on'
      sequence:
        - action: light.turn_on
          data_template:
            # Only turn on one hall light during night mode as the other shines directly into the bed.
            entity_id: >
              {% if is_state('binary_sensor.night', 'on') %}
              light.hall_storage
              {% else %}
              light.flur
              {% endif %}
  # No more motion detected
  default:
    - action: light.turn_off
      data:
        entity_id: light.flur
        transition: 3