---
alias: Door Battery Critical
id: 4bf4f447-ce96-44ae-9420-b4f6ec4b694c
description: Notifies when a water leak is detected in the storage room.
mode: single
variables:
  message: "⚠️ Wohngstür-Nuki muss geladen werden!"
trigger:
  platform: state
  entity_id: binary_sensor.door_appartment_battery_critical
  to: 'on'
action:
  - action: notify.telegram_group
    data:
      message: "{{ message }}"
