---
mode: yaml
resources: !include_dir_list resources
dashboards:
  lovelace-admin:
    mode: yaml
    filename: lovelace/dashboards/admin.yaml
    title: Administration
    icon: mdi:cog
    show_in_sidebar: true
    require_admin: true