---
alias: Button Bathroom
id: a6ef9936-90d0-4502-899b-bea3e3cbf1bc
mode: queued
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:15:8d:00:01:d8:db:30"
action:
  choose:
    # Single Click
    - conditions:
      - "{{ trigger.event.data.args.click_type == 'single' }}"
      sequence:
        - action: light.toggle
          data:
            entity_id: light.bath_ceiling
