---
alias: Light Motion Bath
id: 92ba99f0-2822-4fad-9621-7d218276cedc
description: Turn on the light in the bath when presence is detected or turn it off if there is no motion.
mode: single
trigger:
  - trigger: homeassistant
    event: start
  - trigger: event
    event_type: automation_reloaded
  - trigger: state
    entity_id:
      - binary_sensor.presence_bath
      - alarm_control_panel.ha_alarm
  - trigger: state
    entity_id: binary_sensor.presence_bath
    to: 'off'
    for:
      minutes: 4
action:
  choose:
    # Motion detected
    - conditions:
        - condition: state
          entity_id: binary_sensor.presence_bath
          state: 'on'
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: disarmed
        - condition: numeric_state
          entity_id: sensor.illuminance_bath
          below: 25
      sequence:
        - action: light.turn_on
          data:
            transition: 3
            entity_id: light.bath_ceiling
    # No more motion detected
    - conditions:
      - condition: state
        entity_id: binary_sensor.presence_bath
        state: 'off'
        for: '00:04:00'
      sequence:
        - action: light.turn_off
          entity_id: light.bath_ceiling