---
alias: NFC Bathroom
id: e9841d07-7572-445f-a227-aa2089a1acb8
mode: single
trigger:
  - platform: tag
    tag_id: e9841d07-7572-445f-a227-aa2089a1acb8
action:
  - service: script.play_radio
    data:
      station: bremen_next (playlist)
  - service: media_player.turn_on
    entity_id: media_player.bath_homepod_mini
