---
alias: 3D Printer Done
mode: queued
id: a15c30f7-804f-43d7-aca4-f0e48eaa735f
description: Send a notice when 3D print is done
trigger:
  - platform: state
    entity_id: binary_sensor.octoprint_printing
    to: "off"
    from: "on"
action:
  choose:
    - conditions:
        - condition: state
          entity_id: input_boolean.ender3_v2_automatic_power_off
          state: 'on'
      sequence:
        - service: switch.turn_off
          entity_id: switch.ender3_v2
        - service: input_boolean.turn_off
          entity_id: input_boolean.ender3_v2_automatic_power_off
        - service: notify.telegram_jannis
          data:
            message: "Your 3D print is complete"
            title: "Print Complete"
  default:
    - service: notify.telegram_jannis
      data:
        message: "Your 3D print is complete"
        title: "Print Complete"
  