---
alias: Storage Smoke
id: 66b85a6c-b8a4-4f91-80b1-c12a9b3bc398
description: Notifies when a smoke is detected in the storage room.
mode: restart
trigger:
  trigger: state
  entity_id: binary_sensor.storage_smoke_sensor
  to: 'on'
action:
  - action: notify.telegram_group
    data:
      message: ⚠️ Rauch im Abstellraum erkannt!
  - action: notify.apple_all
    data:
      message: ⚠️ Rauch im Abstellraum erkannt!
      push:
        sound:
          name: "default"
          critical: 1
          volume: 1.0