---
alias: Washing Machine Done
id: df299391-717e-4b8a-ae57-30fd87931415
description: Notifies when the washing machine is done.
mode: restart
trigger:
  trigger: state
  entity_id: binary_sensor.washing_machine
  from: 'off'
  to: 'on'
action:
  action: notify.telegram_group
  data:
    message: "👚👕 Die Waschmaschine ist fertig."
