---
alias: Washing Machine Changed
id: acc9d99d-b549-4250-bbc0-56c051aaaf8f
mode: restart
description: Washing machine or dishwasher started or finished
trigger:
  platform: state
  entity_id: binary_sensor.washing_machine
variables:
  from_state: "{{ trigger.from_state.state }}"
  to_state: "{{ trigger.to_state.state }}"
  name: "{{ trigger.entity_id.split('.', 1)[1] }}"
condition: "{{ (to_state == 'on' and from_state == 'off') or (to_state == 'off' and from_state == 'on') }}"
action:
  action: input_datetime.set_datetime
  data:
    entity_id: "input_datetime.{{ name }}_{{ to_state }}"
    timestamp: "{{ now().timestamp() }}"
