---
alias: Storage Water Leak
id: 0f96fe64-1909-4d54-96e3-cd649a9e466e
description: Notifies when a water leak is detected in the storage room.
mode: restart
variables:
  message: "⚠️ Wasser im Abstellraum erkannt!"
trigger:
  trigger: state
  entity_id: binary_sensor.storage_water
  to: 'on'
action:
  - action: notify.telegram_group
    data:
      message: "{{ message }}"
  - action: notify.apple_all
    data:
      message: "{{ message }}"
      push:
        sound:
          name: "default"
          critical: 1
          volume: 1.0