---
alias: Turn off LMS music
description: Turns off the music system, when all outputs have been turned off for a minute.
id: a0835b1b-bc91-46cb-ab59-e98358d15050
mode: single
trigger:
  - platform: state
    entity_id: media_player.lms_outputs
    to: 'off'
    for:
      minutes: 5
  - platform: state
    entity_id: media_player.lms_all
    to: 'idle'
    for:
      minutes: 5
action:
  - service: media_player.media_stop
    entity_id:
      - media_player.lms_all
  - service: media_player.turn_off
    entity_id:
      - media_player.lms_outputs
