homeassistant:
  name: Home

  internal_url: !secret internal_url_http
  external_url: !secret external_url_http

  # Localization and zone configuration
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  unit_system: metric
  time_zone: Europe/Berlin

  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - 10.0.5.0/24
        - 10.1.5.0/24
        - 10.0.10.0/24
        - 10.0.20.0/24
      trusted_users:
        10.0.5.31: !secret jannis_id
        10.0.5.32: !secret jannis_id
        10.0.5.41: !secret jannis_id
        10.0.5.43: !secret jannis_id
        10.0.5.35: !secret hannah_id
        10.0.5.61: !secret hannah_id
        10.0.5.62: !secret hannah_id
        10.0.20.31: !secret kitchenpanel_id
      allow_bypass_login: true
    - type: homeassistant