---
sensor:
  - platform: version
  # Sensor to track available updates for supervisor & addons
  - platform: command_line
    name: Supervisor updates
    command: 'curl http://supervisor/supervisor/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version,"addons":[.data.addons[] | select(.version != .installed)]}'''
    value_template: "{{ value_json.addons | length }}"
    json_attributes:
    - newest_version
    - current_version
    - addons

binary_sensor:
  - platform: template
    sensors:
      # True if there's an update available for supervisor
      updater_supervisor:
        friendly_name: 'Updater - Supervisor'
        device_class: problem
        entity_id:
        - sensor.supervisor_updates
        value_template: "{{ state_attr('sensor.supervisor_updates', 'current_version') != state_attr('sensor.supervisor_updates', 'newest_version') }}"
        availability_template: "{{ (states('sensor.supervisor_updates') | int(-1)) > -1 }}"

      # True if there's updates available for any HACS components
      updater_hacs:
        friendly_name: 'Updater - HACS'
        device_class: problem
        entity_id:
        - sensor.hacs
        value_template: "{{ states('sensor.hacs') | int > 0 }}"

      # True if there's updates available for any addons
      updater_addons:
        friendly_name: 'Updater - Addons'
        device_class: problem
        entity_id:
        - sensor.supervisor_updates
        value_template: "{{ states('sensor.supervisor_updates') | int > 0 }}"

automation:
  # Update is available - un-acknowledgeble, auto-dismiss, me only
  # Wait 5 minutes before first to give core config check time to run
  - alias: ha_update_available
    id: 471b95f0-f445-4bd6-a003-f46d7188e808
    trigger:
      platform: state
      entity_id: binary_sensor.updater
      to: 'on'
    action:
      service: persistent_notification.create
      data_template:
        title: 'Update for HA available'
        message: "New version is {{ state_attr('binary_sensor.updater', 'newest_version') }}. Currently on {{ states('sensor.current_version') }}"

  # Supervisor update is available - un-acknowledgeable, auto-dismiss, me only
  - alias: supervisor_update_available
    id: fc9f3300-a7fd-4fd7-a264-e008677714f2
    trigger:
      platform: state
      entity_id: binary_sensor.updater_supervisor
      to: 'on'
    action:
      service: persistent_notification.create
      data_template:
        title: 'Update for HA Supervisor available'
        message: "New version is {{ state_attr('sensor.supervisor_updates', 'newest_version') }}. Currently on {{ state_attr('sensor.supervisor_updates', 'current_version') }}"

  # HACS repos have updates available - unacknowledgeable, auto-dismiss, me only
  - alias: hacs_update_available
    id: ded400d4-ed4b-4851-ad50-1438ab7aee91
    trigger:
      platform: state
      entity_id: binary_sensor.updater_hacs
      to: 'on'
    action:
      service: persistent_notification.create
      data_template:
        title: "Updates available in {{ states('sensor.hacs') }} HACS repo{% if states('sensor.hacs') | int > 1 %}s{% endif %}"
        message: ""

  # Addons have updates available - unacknowledgeable, auto-dismiss, me only
  - alias: addon_update_available
    id: 47b167ff-56f6-4c21-a943-f90ac9438bb6
    trigger:
      platform: state
      entity_id: binary_sensor.updater_addons
      to: 'on'
    action:
      service: persistent_notification.create
      data_template:
        title: "Updates available for {{ states('sensor.supervisor_updates') }} HA addon{% if states('sensor.supervisor_updates') | int > 1 %}s{% endif %}"
        message: ""

  - alias: Check config with update
    id: 4f6fba9b-d96a-4062-8c04-9425a2ef3aaf
    description: Starts the check config addon when an update becomes available
    trigger:
    - entity_id: binary_sensor.updater
      platform: state
      to: 'on'
    condition: []
    action:
    - data:
        addon: core_check_config
      service: hassio.addon_start
