---
alias: Button Office
id: da3e3cb9-4f13-4d65-9d4c-f684888c2398
mode: queued
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:15:8d:00:01:d8:db:30"
action:
  choose:
    # Single Click
    - conditions:
      - "{{ trigger.event.data.args.click_type == 'single' }}"
      sequence:
        - service: light.toggle
          entity_id: light.playbar
    # Long Hold
    - conditions:
      - "{{ trigger.event.data.command == 'hold' }}"
      sequence:
        - service: light.turn_off
          entity_id:
            - light.playbar
            - light.office_ceiling