---
alias: Close the blinds
id: 41f7b145-78cd-4da8-8f94-583f478148d3
mode: single
trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: CLOSE_BLINDS
action:
  - service: cover.set_cover_position
    data:
      entity_id: cover.office
      position: 25
