---
alias: Turn on Office Star
id: 97cd7f51-6330-4d70-867b-c727fd0acad4
mode: single
trigger:
  - trigger: sun
    event: sunset
    offset: "-00:30:00"
  # Sunrise
  - trigger: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: 5
  - trigger: state
    entity_id: binary_sensor.alarm_clock_triggered_today
  - trigger: state
    entity_id: binary_sensor.home
condition:
  - condition: state
    entity_id: binary_sensor.home
    state: "on"
  - condition: state
    entity_id: binary_sensor.alarm_clock_triggered_today
    state: "on"
action:
  - delay: "00:01:00"
  - choose:
      # It's dark outside
      - conditions:
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            below: 5
        sequence:
          - action: light.turn_on
            entity_id: light.office_star
    default:
      action: light.turn_off
      entity_id: light.office_star