---
alias: Wall Switch Office
id: 22f61e24-7ea8-4fbf-80ab-6d1ee3816928
mode: queued
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:17:88:01:0b:01:65:a4"
action:
  choose:
    # Wall Switch Toggle
    - conditions:
      - "{{ trigger.event.data.command == 'left_press' }}"
      sequence:
        - action: light.toggle
          entity_id: light.office_ceiling
