---
alias: Alarm clock triggered today off at midnight
description: Turns off the toggle which is used to check whether the alarm clock has been triggered today.
id: d29a9e75-247d-4031-a132-b7c32cbe3a99
mode: single
trigger:
  platform: time
  at: '00:00:00'
action:
  service: input_boolean.turn_off
  entity_id:
    - input_boolean.alarm_clock_triggered_today
    - input_boolean.alarm_clock_on
    - input_boolean.alarm_clock_left_bed