---
alias: Morning music kitchen
description: Turns off the music in the bed room in the morning when there is motion in the hall.
id: bdd8c935-07b1-4a67-9e99-d8b99882cbcb
mode: single
trigger:
  platform: state
  entity_id: binary_sensor.presence_kitchen
  to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.alarm_clock_left_bed
    state: 'on'
  - "{{ not is_state('media_player.kitchen_homepod_mini', 'on') }}"
action:
  service: script.bremen_next_kitchen
