---
alias: Morning music kitchen
description: Turns off the music in the bed room in the morning when there is motion in the hall.
id: bdd8c935-07b1-4a67-9e99-d8b99882cbcb
mode: single
trigger:
  platform: state
  entity_id: binary_sensor.kitchen_human_presence
  to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.alarm_clock_left_bed
    state: 'on'
  - "{{ not is_state('media_player.lms_kitchen', 'playing') }}"
action:
  service: script.play_radio_lms
  data:
    player: media_player.lms_kitchen
    volume_level: 25
    station: Bremen Next
