---
alias: Motion hall alarm clock off
description: Turns off the music in the bed room in the morning when there is motion in the hall.
id: c62fbc9d-c695-4ed1-8257-fe9ff0635978
mode: single
trigger:
  platform: state
  entity_id: binary_sensor.presence_hall
  to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.alarm_clock_on
    state: 'on'
action:
  - service: light.turn_off
    data:
      entity_id: light.go
      transition: 5
  - service: switch.turn_on
    entity_id: switch.living_access_point
  - service: media_player.turn_off
    entity_id: media_player.bed_homepod_mini
  - service: input_boolean.turn_off
    entity_id: input_boolean.alarm_clock_on
  - service: lock.unlock
    entity_id: lock.door_apartment
  - service: input_boolean.turn_on
    entity_id: input_boolean.alarm_clock_left_bed
  - delay: 00:45:00
  - service: input_boolean.turn_off
    entity_id: input_boolean.alarm_clock_left_bed
