---
alias: Motion hall alarm clock off
description: Turns off the music in the bed room in the morning when there is motion in the hall.
id: c62fbc9d-c695-4ed1-8257-fe9ff0635978
mode: single
trigger:
  platform: state
  entity_id: binary_sensor.presence_hall
  to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.alarm_clock_on
    state: 'on'
action:
  - action: light.turn_off
    data:
      entity_id:
        - light.go
        - light.bed_fado
      transition: 5
  - action: switch.turn_on
    entity_id: switch.living_access_point
  - action: media_player.volume_set
    data:
      entity_id: media_player.mass_bed
      volume_level: 0.15
  - action: media_player.media_stop
    entity_id: media_player.mass_bed
  - delay: 00:15:00
  #- action: lock.unlock
  #  entity_id: lock.door_apartment
  - delay: 00:15:00
  - action: input_boolean.turn_off
    entity_id: input_boolean.alarm_clock_on
