input_boolean:
  christmas_mode:
  night_mode:

binary_sensor:
  - platform: template
    sensors:
      night:
        device_class: light
        value_template: >
          {{ is_state('input_boolean.night_mode', 'on') or (is_state('lock.door_apartment', 'locked') and is_state('binary_sensor.home', 'on') and (is_state('sun.sun', 'below_horizon') or (now().hour < 6 and now().hour > 22)) and is_state('input_boolean.alarm_clock_on', 'off')) }}