alias: Schiller Printing finished
id: c8d59b4b-c8c5-4a50-a705-b796b86c07c2
mode: single
trigger:
  - trigger: state
    entity_id: sensor.schiller_print_status
    from: running
action:
  choose:
    - conditions:
      - "{{ trigger.to_state.state == 'finish' }}"
      sequence:
        - action: notify.send_message
          data:
            entity_id: notify.telegram_bot_7823793696_374596217
            message: "Schiller ist fertig."
        - action: switch.turn_off
          entity_id: switch.schiller
    - conditions:
      - "{{ trigger.to_state.state == 'pause' }}"
      sequence:
        - action: notify.send_message
          data:
            entity_id: notify.telegram_bot_7823793696_374596217
            message: "Schiller ist pausiert."
