alias: Apple Watch Vacuum
mode: parallel
id: ae93e1d4-be70-4e61-a6c5-9673da327507
description: Apple Watch Staubstauger
trigger:
  platform: event
  event_type: ios.action_fired
  event_data:
    actionName: Vacuum
action:
  - service: notify.apple
    data:
      message: "Staubsauger"
      data:
        actions:
          - action: VACUUM
            title: Saugen
          - action: MOP
            title: Wischen
          - action: STOP
            title: Stop
  - wait_for_trigger:
      platform: event
      event_type: mobile_app_notification_action
    timeout: "00:00:20"
    continue_on_timeout: false
  - variables:
      option: "{{ wait.trigger.event.data.action }}"
  - choose:
    - conditions: "{{ option == 'VACUUM' }}"
      sequence:
        service: vacuum.start
        entity_id: vacuum.glenn
    - conditions: "{{ option == 'MOP' }}"
      sequence:
        service: script.glenn_mop
    - conditions: "{{ option == 'STOP' }}"
      sequence:
        - service: vacuum.stop
          entity_id: vacuum.glenn
