binary_sensor:
  - platform: mqtt
    name: "Gaming - Connected"
    state_topic: "iotlink/workgroup/gaming/lwt"
    value_template: "{{ value }}"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: "connectivity"
    qos: 1

sensor:
  - platform: mqtt
    name: "Gaming - CPU Usage"
    state_topic: "iotlink/workgroup/gaming/windows-monitor/stats/cpu/usage"
    unit_of_measurement: '%'
    icon: mdi:speedometer
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/gaming/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

  - platform: mqtt
    name: "Gaming - RAM Usage"
    state_topic: "iotlink/workgroup/gaming/windows-monitor/stats/memory/usage"
    unit_of_measurement: '%'
    icon: mdi:memory
    value_template: "{{ value }}"
    availability_topic: "iotlink/workgroup/gaming/lwt"
    payload_available: "ON"
    payload_not_available: "OFF"
    qos: 1

switch:
  - platform: template
    switches:
      gaming:
        friendly_name: "Gaming"
        value_template: "{{ is_state('binary_sensor.gaming_connected', 'on') }}"
        turn_on:
          service: script.gaming_wake
        turn_off:
          service: script.gaming_shutdown
        icon_template: mdi:laptop

script:
  gaming_wake:
    alias: "Gaming - Wake"
    sequence:
      # Not working for now
      - service: switch.turn_on
        entity_id: switch.computer

  gaming_shutdown:
    alias: "Gaming - Shutdown"
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/gaming/commands/shutdown"
          payload: ""