binary_sensor:
  - platform: template
    sensors:
      washing_machine:
        friendly_name: Washing machine
        value_template: >
          {{ states("sensor.washing_machine_current_consumption") | default(0) | float(0) > 6 }}
        delay_off: "00:02:30"
        icon_template: >
          {% if is_state("binary_sensor.washing_machine", "on") %}
            mdi:washing-machine
          {% else %}
            mdi:washing-machine-off
          {% endif %}

powercalc:
