# Taken from: https://github.com/basnijholt/home-assistant-config/blob/c54c97912b7a5c527df0e5503e5e36eaa8bfb774/scripts.yaml#L479
script:
  washing_machine_notification:
    mode: single
    variables:
      name: washing_machine
      binary_sensor: "{{ 'binary_sensor.{}'.format(name) }}"
    sequence:
      - variables:
          start_time: "{{ as_timestamp(now()) }}"
      - wait_for_trigger:
          platform: template
          value_template: "{{ is_state(binary_sensor, 'off') }}"
        timeout: "04:00:00"
        continue_on_timeout: false
      - variables:
          end_time: "{{ as_timestamp(now()) }}"
      - variables:
          total_time: "{{ (end_time - start_time) }}"
      - variables:
          minutes: "{{ (total_time / 60) | round(0) | int }}"
      - condition: "{{ minutes >= 5 }}"
      - action: notify.telegram_group
        data:
          message: "👚👕 Die Waschmaschine ist fertig. Sie hat {{ minutes }} Minuten gebraucht."

binary_sensor:
  - platform: template
    sensors:
      washing_machine:
        friendly_name: Washing machine
        value_template: >
          {{ states("sensor.washing_machine_current_consumption") | default(0) | float(0) > 6 }}
        delay_off: "00:02:30"
        icon_template: >
          {% if is_state("binary_sensor.washing_machine", "on") %}
            mdi:washing-machine
          {% else %}
            mdi:washing-machine-off
          {% endif %}

powercalc:
