sensor:
  - platform: integration
    source: sensor.washing_machine_current_consumption
    unique_id: washing_machine_energy
    name: Waschmaschine
    round: 2
    unit_prefix: k

  - platform: template
    sensors:
      hannah_desk_voltage:
        value_template: >-
          {{ states.switch.bed_hannah_desk.attributes.voltage }}
        unit_of_measurement: 'V'
      hannah_desk_current:
        value_template: >-
          {{ states.switch.bed_hannah_desk.attributes.current }}
        unit_of_measurement: 'mA'
      hannah_desk_current_consumption:
        value_template: >-
          {{ states.switch.bed_hannah_desk.attributes.current_consumption }}
        unit_of_measurement: 'W'
        device_class: 'power'

  - platform: integration
    source: sensor.hannah_desk_current_consumption
    unique_id: hannah_desk_energy
    name: Hannah Schreibtisch
    round: 2
    unit_prefix: k

# Taken from: https://github.com/basnijholt/home-assistant-config/blob/c54c97912b7a5c527df0e5503e5e36eaa8bfb774/scripts.yaml#L479
script:
  washing_machine_notification:
    mode: parallel
    max: 20
    variables:
      name: washing_machine
      binary_sensor: "{{ 'binary_sensor.{}'.format(name) }}"
    sequence:
      - variables:
          start_time: "{{ as_timestamp(now()) }}"
      - wait_for_trigger:
          platform: template
          value_template: "{{ is_state(binary_sensor, 'off') }}"
        timeout: "04:00:00"
        continue_on_timeout: false
      - variables:
          end_time: "{{ as_timestamp(now()) }}"
      - variables:
          total_time: "{{ (end_time - start_time) }}"
      - variables:
          minutes: "{{ (total_time / 60) | round(0) }}"
      - service: notify.telegram_group
        data:
          message: "👚👕 Die Waschmaschine ist fertig. Sie hat {{ minutes }} Minuten gebraucht."

input_datetime:
  washing_machine_on:
    name: Washing machine last started
    has_date: true
    has_time: true

  washing_machine_off:
    name: Washing machine last done
    has_date: true
    has_time: true

binary_sensor:
  - platform: template
    sensors:
      washing_machine:
        friendly_name: Washing machine
        value_template: >
          {{ states("sensor.washing_machine_current_consumption") | default(0) | float(0) > 6 }}
        delay_off: "00:02:30"
        icon_template: >
          {% if is_state("binary_sensor.washing_machine", "on") %}
            mdi:washing-machine
          {% else %}
            mdi:washing-machine-off
          {% endif %}
  - platform: template
    sensors:
      water_kettle:
        friendly_name: Water Kettle
        value_template: >
          {{ states("sensor.kettle_temp") | default(0) | float(0) > 30 }}
        delay_off: "00:01:00"
