localtuya:
  - host: 10.0.20.51
    device_id: !secret tuya_1_id
    local_key: !secret tuya_1_key
    friendly_name: Plug 1
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: Plug
        id: 1

  - host: 10.0.20.52
    device_id: !secret tuya_2_id
    local_key: !secret tuya_2_key
    friendly_name: Plug 2
    protocol_version: "3.3"
    scan_interval: 30
    entities:
      - platform: switch
        friendly_name: Plug
        id: 1
        current: 18
        current_consumption: 19
        voltage: 20

  - host: 10.0.20.53
    device_id: !secret tuya_3_id
    local_key: !secret tuya_3_key
    friendly_name: Plug 3
    protocol_version: "3.3"
    scan_interval: 30
    entities:
      - platform: switch
        friendly_name: Plug
        id: 1
        current: 18
        current_consumption: 19
        voltage: 20

sensor:
  - platform: template
    sensors:
      victoria_voltage:
        value_template: >-
          {{ states.switch.victoria.attributes.voltage }}
        unit_of_measurement: 'V'
      victoria_current:
        value_template: >-
          {{ states.switch.victoria.attributes.current }}
        unit_of_measurement: 'mA'
      victoria_current_consumption:
        value_template: >-
          {{ states.switch.victoria.attributes.current_consumption }}
        unit_of_measurement: 'W'

  - platform: integration
    source: sensor.victoria_current_consumption
    name: victoria_energy
    round: 2
    unit_prefix: k
