---
device_tracker:
  - platform: snmp
    host: !secret snmp_ip
    community: !secret snmp_community
    baseoid: !secret snmp_baseoid

sensor:
  - platform: snmp
    name: router_gateway_uptime
    host: !secret snmp_ip
    community: !secret snmp_community
    baseoid: 1.3.6.1.2.1.1.3.0
    scan_interval: 2
    value_template: >
      {% set timetick = value  |int(0) %}
      {% set seconds = (timetick / 100) | round(0) | int(0) %}
      {% set days = (seconds / 60 / 60 / 24) | int(0) %}
      {% set hours = ((seconds / 60 / 60) - (days * 24)) | int(0) %}
      {% set minutes = ((seconds / 60 ) - ( hours * 60) - ( days * (24 * 60))) | int(0) %}
      {% if days > 0 %}
        {{ days }}day
      {% endif %}
      {% if hours > 0 %}
        {{ hours }}h
      {% else %}
        {{ 00 }}h
      {% endif %}
      {% if minutes > 0 %}
        {{ minutes }}m
      {% else %}
        {{ 00 }}m
      {% endif %}

  - platform: snmp
    name: router_gateway_load
    host: !secret snmp_ip
    community: !secret snmp_community
    baseoid: 1.3.6.1.4.1.2021.10.1.3.1
    scan_interval: 2
    value_template: "{{ ((value | float(0) * 100) / 4) | round(2) }}" 
    device_class: power_factor
    unit_of_measurement: "%"
