---
alias: Notify Backup Failure
id: 0ae02693-a24e-4b1b-b431-7c50ad1ac940
trigger:
  trigger: event
  event_type: auto_backup.backup_failed
action:
  action: persistent_notification.create
  data:
    title: "Backup Failed."
    message: |-
      Name: {{ trigger.event.data.name }}
      Error: {{ trigger.event.data.error }}