---
alias: Automatic Backup
id: cc806438-32a7-4250-a853-266e6935cfb7
trigger:
  platform: time
  at: "02:00:00"
action:
  action: auto_backup.backup_partial
  data:
    name: "DailyBackup: {{ now().strftime('%a, %-I:%M %p (%d/%m/%Y)') }}"
    password: !secret hassio_snapshot_password
    keep_days: 2
    folders:
      - addons
      - config
      - media
      - ssl
    addons:
      - core_samba
      - core_mariadb
      - core_mosquitto
      - core_letsencrypt
      - d5369777_music_assistant
