---
alias: Automatic Backup
id: cc806438-32a7-4250-a853-266e6935cfb7
trigger:
  platform: time
  at: "02:00:00"
action:
  service: auto_backup.backup
  data:
    name: "DailyBackup: {{ now().strftime('%a, %-I:%M %p (%d/%m/%Y)') }}"
    password: !secret hassio_snapshot_password
    keep_days: 2
    include_folders:
      - addons
      - config
      - media
      - share
      - ssl
    include_addons:
      - core_samba
      - core_mariadb
      - core_mosquitto
      - core_letsencrypt
      - 243ffc37_syncthing
      - ca5234a0_paperless-ngx
      - d5369777_music_assistant
      - db21ed7f_changedetection.io
