---
alias: AVR Turn Off when Idle
id: 4ba47def-0a50-4156-9b4f-97062eb42421
description: Turns off the AVR when its detected to sit idle and consume power
mode: queued
trigger:
  trigger: time_pattern
  minutes: "/5"
condition:
  # TV is off
  - condition: state
    entity_id: media_player.philips_tv
    state: 'off'
    # Apple TV is off
  - condition: state
    entity_id: media_player.apple_tv
    state: 'standby'
  # No music playing on AVR
  - condition: not
    conditions:
    - condition: state
      entity_id: media_player.denon_avr_x1700h
      state: "playing"
    - condition: state
      entity_id: media_player.mass_denon
      state: "playing"
action:
  action: media_player.turn_off
  entity_id: media_player.avr
