---
alias: Button Living
id: 6b4f2245-d39a-4190-a846-c51dffcaae4e
mode: queued
trigger:
  trigger: event
  event_type: zha_event
  event_data:
    device_ieee: "00:15:8d:00:04:26:22:31"
action:
  choose:
    # Left Click
    - conditions:
      - "{{ trigger.event.data.command == 'left_single' }}"
      sequence:
        - action: light.toggle
          entity_id: light.living_wall
    # Left Double Click
    - conditions:
      - "{{ trigger.event.data.command == 'left_double' }}"
      sequence:
        - action: script.tv_hdmi_playstation
    # Left Long Click
    - conditions:
      - "{{ trigger.event.data.command == 'left_long press' }}"
      sequence:
        - action: script.tv_hdmi_nintendoswitch
    # Right Single Click
    - conditions:
      - "{{ trigger.event.data.command == 'right_single' }}"
      sequence:
        - action: light.toggle
          data:
            entity_id: light.living_floor
            transition: 1
    # Right Double Click
    - conditions:
      - "{{ trigger.event.data.command == 'right_double' }}"
      sequence:
        - action: input_boolean.toggle
          entity_id: input_boolean.automatic_ambilight
    # Right Long Click
    - conditions:
      - "{{ trigger.event.data.command == 'right_long press' }}"
      sequence:
        - action: script.toggle_ambilight
