---
alias: Button Living
id: 6b4f2245-d39a-4190-a846-c51dffcaae4e
mode: queued
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:15:8d:00:04:26:22:31"
action:
  choose:
    # Single Click
    - conditions:
      - "{{ trigger.event.data.command == 'left_single' }}"
      sequence:
        - service: light.toggle
          entity_id: light.living_floor_light
    # Double Click
    - conditions:
      - "{{ trigger.event.data.command == 'right_single' }}"
      sequence:
        - service: script.toggle_ambilight_hue
