---
alias: Button Living
id: 6b4f2245-d39a-4190-a846-c51dffcaae4e
mode: queued
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:15:8d:00:04:26:22:31"
action:
  choose:
    # Left Click
    - conditions:
      - "{{ trigger.event.data.command == 'left_single' }}"
      sequence:
        - service: light.toggle
          entity_id: light.living_floor_light
    # Left Double Click
    - conditions:
      - "{{ trigger.event.data.command == 'left_double' }}"
      sequence:
        - service: media_player.select_source
          data:
            entity_id: media_player.philips_tv
            source: 'HDMI 2'
    # Left Long Click
    - conditions:
      - "{{ trigger.event.data.command == 'left_long press' }}"
      sequence:
        - service: media_player.select_source
          data:
            entity_id: media_player.philips_tv
            source: 'HDMI 3'
    # Right Click
    - conditions:
      - "{{ trigger.event.data.command == 'right_single' }}"
      sequence:
        - service: input_boolean.toggle
          entity_id: input_boolean.automatic_ambilight
    # Right Double Click
    - conditions:
      - "{{ trigger.event.data.command == 'right_double' }}"
      sequence:
        - service: light.toggle
          entity_id: light.ambilight
