---
alias: Besta Light
id: adbffe83-7f3e-4a3a-a252-656140234a72
mode: queued
trigger:
  - trigger: state
    entity_id: light.living_wall
  - trigger: state
    entity_id: light.living_floor
  - trigger: sun
    event: sunset
action:
  choose:
    - conditions:
        - condition: and
          conditions:
            - condition: or
              conditions:
              - condition: state
                entity_id: light.living_wall
                state: "on"
              - condition: state
                entity_id: light.ambilight
                state: "on"
              - condition: state
                entity_id: light.living_floor
                state: "on"
            - condition: numeric_state
              entity_id: sensor.illuminance
              below: 1500
      sequence:
        - action: light.turn_on
          data:
            entity_id: light.living_besta
            transition: 2
  default:
    - action: light.turn_off
      data:
        entity_id: light.living_besta
        transition: 1
