---
alias: Reset Automatic Ambilight
description: Reactivates the automatic ambilight automation daily.
id: 66748e10-80a2-4b60-a4c5-386ae416d173
mode: single
trigger:
  platform: time
  at: '04:00:00'
action:
  action: input_boolean.turn_on
  entity_id: input_boolean.automatic_ambilight
