---
alias: Toggle Ambilight+Hue
id: 7564e411-05b1-40a3-a675-fec358c81b1a
description: Toggle Ambilight+Hue depending on the sun level.
mode: queued
trigger:
  platform: time_pattern
  minutes: "/2"
condition:
  - condition: state
    entity_id: media_player.apple_tv
    state: playing
  - condition: state
    entity_id: input_boolean.automatic_ambilight_hue
    state: 'on'
action:
  choose:
    # Dark outside.
    - conditions:
        - condition: or
          conditions:
            - condition: time
              after: '21:30:00'
            - condition: sun
              after: sunset
            - condition: sun
              before: sunrise
      sequence:
        - service: switch.turn_on
          entity_id: switch.ambilighthue
  # Somewhat bright outside.
  default:
    service: switch.turn_off
    entity_id: switch.ambilighthue
