---
alias: Toggle Ambilight
id: 7564e411-05b1-40a3-a675-fec358c81b1a
description: Toggle Ambilight depending on the illuminance level.
mode: queued
trigger:
  trigger: time_pattern
  minutes: "/2"
condition:
  - condition: state
    entity_id: remote.65oled856_12_remote
    state: 'on'
  - condition: or
    conditions:
      - condition: state
        entity_id: remote.apple_tv
        state: 'on'
      - condition: state
        entity_id: media_player.avr
        state: 'on'
      - condition: state
        entity_id: switch.ps5_power
        state: 'on'
  - condition: state
    entity_id: input_boolean.automatic_ambilight
    state: 'on'
action:
  choose:
    # Dark outside.
    - conditions:
        - condition: numeric_state
          entity_id: sensor.illuminance
          below: 2000
      sequence:
        - action: light.turn_on
          data:
            entity_id: light.ambilight
            effect: "FOLLOW_VIDEO: NATURAL"
    - conditions:
      - condition: state
        entity_id: light.ambilight
        state: "on"
      sequence:
        - action: light.turn_off
          entity_id: light.ambilight
