---
alias: Toggle Ambilight
id: 7564e411-05b1-40a3-a675-fec358c81b1a
description: Toggle Ambilight depending on the sun level.
mode: queued
trigger:
  platform: time_pattern
  minutes: "/2"
condition:
  - condition: state
    entity_id: media_player.philips_tv
    state: 'on'
  - condition: state
    entity_id: input_boolean.automatic_ambilight
    state: 'on'
action:
  choose:
    # Dark outside.
    - conditions:
        - condition: or
          conditions:
            - condition: time
              after: '21:00:00'
            - condition: sun
              after: sunset
            - condition: sun
              before: sunrise
      sequence:
        - service: light.turn_on
          data:
            entity_id: light.ambilight
            effect: Standard
  # Somewhat bright outside.
  default:
    service: light.turn_off
    entity_id: light.ambilight
