- title: Einstellungen
  icon: mdi:cog
  path: settings
  cards:
    - type: vertical-stack
      cards:
        - !include 
          - ../includes/header.yaml
          - title: Wecker

        - type: vertical-stack
          cards:
            - title: Funktionen
              type: custom:mushroom-title-card
            - type: custom:time-picker-card
              entity: input_datetime.alarm_time
            - type: grid
              columns: 2
              square: false
              cards:
                - type: custom:mushroom-entity-card
                  entity: input_boolean.alarm_clock
                  tap_action:
                    action: toggle
                  name: Wecker
                - type: custom:mushroom-entity-card
                  entity: input_boolean.motion_sensor
                  tap_action:
                    action: toggle
                  name: Bewegungsmelder
                - type: custom:mushroom-entity-card
                  entity: input_boolean.vacation_mode
                  tap_action:
                    action: toggle
                  name: Urlaub
                - type: custom:mushroom-entity-card
                  entity: input_boolean.automatic_ambilight
                  tap_action:
                    action: toggle
                  name: Ambilight
                  icon: mdi:light-switch
                - type: custom:mushroom-entity-card
                  entity: automation.vacuum_clean_daily
                  tap_action:
                    action: toggle
                  name: Glenn
                  icon: phu:roborock
                - type: custom:mushroom-entity-card
                  entity: input_boolean.open_house_door_on_ring
                  tap_action:
                    action: toggle

        - type: vertical-stack
          cards:
            - title: Home Feed
              type: custom:mushroom-title-card
            - type: logbook
              title: " "
              entities:
                - alarm_control_panel.ha_alarm
                - binary_sensor.presence_kitchen
                - binary_sensor.presence_hall
                - binary_sensor.contact_office
                - binary_sensor.contact_kitchen
                - binary_sensor.contact_bed
                - binary_sensor.contact_bath
                - binary_sensor.contact_door
                - binary_sensor.contact_living_door
                - binary_sensor.contact_living_window
                - lock.door_house
                - lock.door_apartment
                - binary_sensor.doorbell
