# lovelace_gen
{% set home_feed_entities = [
'alarm_control_panel.ha_alarm',
'binary_sensor.presence_kitchen',
'binary_sensor.presence_hall',
'binary_sensor.contact_office',
'binary_sensor.contact_kitchen',
'binary_sensor.contact_bed',
'binary_sensor.contact_bath',
'binary_sensor.contact_door',
'binary_sensor.contact_living_door',
'binary_sensor.contact_living_window',
] %}
- title: Einstellungen
  icon: mdi:cog
  path: settings
  cards:
    - type: vertical-stack
      cards:
        - !include 
          - ../includes/header.yaml
          - title: Wecker

        - type: vertical-stack
          cards:
            - template: title
              name: Funktionen
              type: 'custom:button-card'
            - type: custom:time-picker-card
              entity: input_datetime.alarm_time
            - !include
              - ../includes/grid.yaml
              - entities: 
                  - entity_id: input_boolean.alarm_clock
                    name: Wecker
                  - entity_id: input_boolean.motion_sensor
                    name: Bewegungsmelder
                  - entity_id: input_boolean.vacation_mode
                    name: Urlaub
                  - entity_id: input_boolean.automatic_ambilight_hue
                    name: Ambi+Hue
                    icon: mdi:light-switch
                  - entity_id: input_boolean.ender3_v2_automatic_power_off
                    name: 3D Ausschalten
                    icon: mdi:printer-3d
                  - entity_id: automation.vacuum_clean_daily
                    name: Glenn
                    icon: phu:roborock

        - type: vertical-stack
          cards:
            - template: title
              name: Home Feed
              type: 'custom:button-card'
            - type: logbook
              title: " "
              entities:
                {% for entity in home_feed_entities %}
                - {{ entity }}
                {% endfor %}

        - type: custom:grocy-chores-card
          entity: sensor.grocy_chores
          title: Aufgaben
          show_last_tracked_by: false
          show_assigned: false
