---
description: Send notification when automations are reloaded
alias: System automation reloaded notification
id: 41f7aec4-17f1-480d-969d-14789cf501f5
mode: single
trigger:
  trigger: event
  event_type: automation_reloaded
action:
  action: notify.send_message
  data:
    entity_id: notify.telegram_bot_7823793696_1002384392545
    message: Home Assistant reloaded all automations 🤖
