---
description: Send notification when automations are reloaded
alias: System automation reloaded notification
id: 41f7aec4-17f1-480d-969d-14789cf501f5
mode: single
trigger:
  platform: event
  event_type: automation_reloaded
action:
  action: notify.telegram_jannis
  data:
    message: Home Assistant reloaded all automations 🤖
