---
alias: Clear logs
description: Clears the home assistant logs every sunday.
id: ea3754a8-9dc6-4ef8-81eb-29f751071dd4
mode: single
trigger:
  trigger: time
  at: '04:00:00'
condition:
  condition: time
  weekday: sun
action:
  action: system_log.clear