---
alias: home_change_music_light_off
description: Turn off light and music when leaving the house
id: 0fc4b756-3801-4143-a1f3-67e92f56bba9
mode: queued
trigger:
  platform: state
  entity_id: binary_sensor.home
  to: 'off'
action:
  - service: media_player.turn_off
    entity_id: media_player.lms_all
  - service: light.turn_off
    entity_id: light.color
