alias: Refresh On Call Calendar
id: bb63538d-5833-460c-949a-aebb1818bc23
description: "Downloads my latest on-call schedule and load it."
mode: single
trigger:
  - platform: time_pattern
    minutes: "0"
action:
  - action: shell_command.update_on_call_calendar
  - action: homeassistant.reload_config_entry
    target:
      entity_id: calendar.on_call
