---
description: Send notification when scenes are reloaded
alias: Systeme scene reloaded notification
id: c8dffcdc-6d66-4bcf-b823-19a0bc2b1a97
mode: single
trigger:
  platform: event
  event_type: scene_reloaded
action:
  action: notify.telegram_jannis
  data:
    message: Home Assistant reloaded all scenes 🌈
