---
description: Send notification on Home Assistant stop
alias: System shutdown notification
id: 761953d0-50cc-4f0b-81ff-3f305223ce38
mode: single
trigger:
  trigger: homeassistant
  event: shutdown
action:
  - action: notify.telegram_jannis
    data:
      message: Home Assistant is shutting down... Bye!
