---
description: Send notification on Home Assistant stop
alias: System shutdown notification
id: 761953d0-50cc-4f0b-81ff-3f305223ce38
mode: single
trigger:
  trigger: homeassistant
  event: shutdown
action:
  - action: notify.send_message
    data:
      entity_id: notify.telegram_bot_7823793696_1002384392545
      message: Home Assistant is shutting down... Bye!
