---
alias: Speedtest
id: 6bfc5074-8144-4285-94d7-c574bc7e0819
description: Runs a speedtest when the main pc is turned off.
mode: single
trigger:
  platform: time_pattern
  minutes: '/5'
condition:
  condition: state
  entity_id: binary_sensor.gaming_connected
  state: 'off'
action:
  service: speedtestdotnet.speedtest
