---
alias: System Let's Encrypt Renewal
description: Checks whether the SSL certs needs to be renewed. If that is the case, start the Let's Encrypt add-on.
id: 6d3fd9b0-eb21-435b-b85e-bb14d128a843
trigger:
  platform: time
  at: '04:00:00'
condition:
  condition: template
  value_template: "{{as_timestamp(states('sensor.cert_expiry_timestamp')) - as_timestamp(now()) < 30 * 24 * 60 * 60}}"
action:
  - action: hassio.addon_restart
    data:
      addon: core_letsencrypt
  - delay: 00:05:00
  - action: homeassistant.restart
