---
description: Send notification on Home Assistant start
alias: System start notification
id: 104463f6-7524-48d9-bbe5-2bb09017e946
mode: single
trigger:
  platform: homeassistant
  event: start
action:
  action: notify.telegram_jannis
  data:
    message: Home Assistant finished starting up again 🎉
