---
description: Send notification on Home Assistant start
alias: System start notification
id: 104463f6-7524-48d9-bbe5-2bb09017e946
mode: single
trigger:
  trigger: homeassistant
  event: start
action:
  action: notify.send_message
  data:
    entity_id: notify.telegram_bot_7823793696_1002384392545
    message: Home Assistant finished starting up again 🎉
