---
id: 9f043340-ce18-4fbc-9748-72a02beaa454
alias: Notify when household tasks are due
trigger:
  - platform: time
    at: "10:00:00"
mode: single
action:
  - repeat:
      for_each: "{{ expand(states.input_button) | map(attribute='entity_id') | select('search', 'chore') | list }}"
      sequence:
        - variables:
            task_id: "{{ repeat.item | replace('input_button.', '', 1) }}"
            button: "{{ 'input_button.' + task_id }}"
            text: "{{ 'input_text.' + task_id }}"
            next_due: "{{ states(button) | as_datetime + timedelta(days=(states(text) | int) - 1) }}"
        - condition: template
          value_template: "{{ next_due | as_datetime < now() }}"
        - service: notify.telegram_group
          data:
            message: "🧹 {{ state_attr(button, 'friendly_name') }} muss erledigt werden."
