---
id: 4e4f71ca-574f-4397-8e22-46e5329cd853
alias: Chores Due Notification
description: Notify when household tasks are due
trigger:
  - trigger: state
    entity_id: sensor.chores_due
condition:
  - condition: template
    value_template: "{{ trigger.from_state.state | int < trigger.to_state.state | int }}"
mode: single
action:
  - action: notify.telegram_group
    data_template:
      message: |
        Fällige Aufgabe(n):
        {%- for activity in states.sensor | selectattr('attributes.integration', 'eq', 'activity_manager') -%}
        {%- if activity.state|as_datetime < now() -%}
        - {{ activity.name }}
        {{ "\n" }}
        {%- endif -%}
        {%- endfor %}
