---
alias: Home Assistant starts ➔ Update Group - Chores
id: 5f873cef-abdc-4124-be79-9c6151e7df3d
trigger:
- platform: homeassistant
  event: start
- platform: event
  event_type: call_service
  event_data:
    domain: group
    service: reload
action:
- service: group.set
  data_template:
    name: All Chores
    object_id: chores
    entities: |
      {% set ns = namespace(entities=[]) %}
      {% for s in states.input_button if s.object_id.startswith('chore_') %}
        {% set ns.entities = ns.entities + [ s.entity_id ] %}
      {% endfor %}
      {{ ns.entities }}
