---
id: 9f043340-ce18-4fbc-9748-72a02beaa454
alias: Notify when household tasks are due
trigger:
  - platform: time
    at: "17:00:00"
mode: single
action:
  - variables:
      chores: "{{ expand(states.input_button) |map(attribute='entity_id') |select('search', 'chore') }}"
  - repeat:
      count: "{{ chores | count }}"
      sequence:
        - variables:
            chore: '{{ chores[repeat.index - 1] }}'
        - service: script.chore_notify
          data:
            task_id: "{{ chore }}"
