---
alias: Glenn ask to start cleaning
id: 9fc303a8-4e3e-4585-bcf3-514bcb5c433a
mode: single
trigger:
  platform: time
  at: '13:00'
condition:
  - condition: not
    conditions:
      - condition: time
        weekday: sun
      - condition: state
        entity_id: vacuum.glenn
        state: cleaning
  - condition: state
    entity_id: person.hannah
    state: home
  - condition: state
    entity_id: input_boolean.cleaned_today
    state: 'off'
action:
  service: notify.mobile_app_eml_l29
  data:
    message: "Soll Glenn fahren?"
    data:
      actions:
        - action: RUN_VACUUM
          title: Fahren
