---
alias: Vacuum maintenance checks
description: Vacuum maintenance checks
id: be74aead-ac55-4b5f-8005-6941a41c273c
mode: single
trigger:
  platform: state
  entity_id: vacuum.valetudo_glenn
  to: docked
action:
  choose:
  - conditions:
    - condition: numeric_state
      entity_id: sensor.valetudo_glenn_main_brush
      below: 10
    sequence:
      service: notify.telegram_group
      data:
        message: 🔧 Glenns Hauptbrüste muss bald getauscht werden.
  - conditions:
    - condition: numeric_state
      entity_id: sensor.valetudo_glenn_right_brush
      below: 10
    sequence:
      service: notify.telegram_group
      data:
        message: 🔧 Glenns Seitenbürste müssen bald getauscht werden.
  - conditions:
    - condition: numeric_state
      entity_id: sensor.valetudo_glenn_main_filter
      below: 10
    sequence:
      service: notify.telegram_group
      data:
        message: 🔧 Glenns Filter muss bald getauscht werden.
  - conditions:
    - condition: numeric_state
      entity_id: sensor.valetudo_glenn_sensor_cleaning
      below: 10
    sequence:
      service: notify.telegram_group
      data:
        message: 🔧 Glenns Sensoren müssen bald gereinigt werden.
