---
alias: Vacuum reset cleaned today
description: Reset daily cleaning flag
id: 4d6635ae-56d6-4d01-80bc-a9eac34ee646
mode: single
trigger:
  trigger: time
  at: '00:00:00'
action:
  - action: input_boolean.turn_off
    entity_id: binary_sensor.glenn_cleaned_today
