---
alias: Start Cleaning Selected Room
id: bd0a351d-b872-4088-b8cf-61e496cb1da2
mode: single
trigger:
- platform: state
  entity_id: input_select.glenn_room
  from: 'Select Room'
action:
- service: script.turn_on
  data_template:
    variables:
      room: >
        {% if is_state("input_select.glenn_room", "Abstellraum") %}
          storage
        {% elif is_state("input_select.glenn_room", "Badezimmer") %}
          bath
        {% elif is_state("input_select.glenn_room", "Küche") %}
          kitchen
        {% elif is_state("input_select.glenn_room", "Wohnzimmer") %}
          living
        {% elif is_state("input_select.glenn_room", "Büro") %}
          office
        {% elif is_state("input_select.glenn_room", "Flur") %}
          hall
        {% elif is_state("input_select.glenn_room", "Schlafzimmer") %}
          bed
        {% endif %}
    entity_id: script.glenn_room_cleaning
- service: input_select.select_option
  data:
    entity_id: input_select.glenn_room
    option: "Select Room"
