---
alias: Vacuum cleaning error
description: Vacuum cleaning error
id: 7ceaf2ba-a0ec-4cbf-8ed2-35d93bd096be
mode: single
variables:
  message: "😢 Glenn hat ein Problem: "
trigger:
  trigger: state
  entity_id: vacuum.glenn
  from: cleaning
  to: error
action:
  - action: notify.send_message
    data_template:
      entity_id: notify.telegram_bot_7823793696_374596217
      message: "{{ message }} {{ states('sensor.glenn_error') }}"
  - action: notify.apple_all
    data_template:
      message: "{{ message }} {{ states('sensor.glenn_error') }}"
