---
alias: Vacuum cleaning done
description: Vacuum cleaning done
id: afff179f-e1d9-4e22-9f4b-0a50aa86c693
mode: single
trigger:
  trigger: state
  entity_id: vacuum.glenn
  from: cleaning
  to: returning
action:
  choose:
    # Motion detected
    - conditions:
        - condition: state
          entity_id: binary_sensor.valetudo_glenn_mop_attachment
          state: 'on'
      sequence:
      - action: input_boolean.turn_on
        entity_id: binary_sensor.glenn_cleaned_today
      - action: notify.telegram_group
        data:
          message: "Glenn ist fertig mit dem Wischen. "
    # No mop attachment
  default:
    sequence:
    - action: input_boolean.turn_on
      entity_id: binary_sensor.glenn_cleaned_today
