---
alias: Run the vacuum from an app action
id: 9dc0dc90-75a3-470a-b298-83daae3a9455
mode: single
trigger:
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: RUN_VACUUM
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: RUN_VACUUM
action:
  choose:
    # Door open
    - conditions:
      - condition: state
        entity_id: binary_sensor.contact_bed_room
        state: 'on'
      sequence:
        - service: vacuum.start
          entity_id: vacuum.glenn

  # Door closed
  default:
    service: notify.mobile_app_eml_l29
    data:
      message: "Tür öffnen! Soll Glenn fahren?"
      data:
        actions:
          - action: RUN_VACUUM
            title: Fahren
