---
alias: Vacuum cleaning error
description: Vacuum cleaning error
id: 7ceaf2ba-a0ec-4cbf-8ed2-35d93bd096be
mode: single
variables:
  message: "😢 Glenn hat ein Problem: "
trigger:
  platform: state
  entity_id: vacuum.glenn
  from: cleaning
  to: error
action:
  - service: notify.telegram_group
    data_template:
      message: "{{ message }} {{ states('sensor.glenn_error_description') }}"
  - service: notify.all_devices
    data_template:
      message: "{{ message }} {{ states('sensor.glenn_error_description') }}"
