---
alias: Vacuum cleaning done
description: Vacuum cleaning done
id: afff179f-e1d9-4e22-9f4b-0a50aa86c693
mode: single
trigger:
  platform: state
  entity_id: vacuum.glenn
  from: cleaning
  to: returning
action:
  choose:
    # Motion detected
    - conditions:
        - condition: state
          entity_id: binary_sensor.valetudo_glenn_mop_attachment
          state: 'on'
      sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.cleaned_today
      - service: notify.telegram_group
        message: "Glenn ist fertig mit dem Wischen. "
    # No mop attachment
    - default:
      sequence:
        - service: input_boolean.turn_on
          entity_id: input_boolean.cleaned_today
  
