---
alias: Vacuum reset cleaned today
description: Reset daily cleaning flag
id: 4d6635ae-56d6-4d01-80bc-a9eac34ee646
mode: single
trigger:
  platform: time
  at: '00:00:00'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.cleaned_today
