---
alias: Vacuum cleaning done
description: Vacuum cleaning done
id: afff179f-e1d9-4e22-9f4b-0a50aa86c693
mode: single
trigger:
  platform: state
  entity_id: vacuum.glenn
  from: cleaning
  to: returning
action:
    entity_id: input_boolean.cleaned_today