---
description: Vaccum clean daily
alias: vacuum_clean_daily
id: a64237e2-5c17-4022-aff6-fa8d16a19738
mode: single
trigger:
  - platform: time
    at: '10:00'
  - platform: state
    entity_id: binary_sensor.home
    to: 'off'
condition:
  - condition: or
    conditions:
      - condition: time
        after: '09:00'
        before: '12:00'
      - condition: time
        after: '13:00'
        before: '20:00'
  - condition: state
    entity_id: binary_sensor.home
    state: 'off'
  - condition: state
    entity_id: input_boolean.cleaned_today
    state: 'off'
action:
  action: vacuum.start
  entity_id: vacuum.glenn
