---
alias: Ask to close the blinds at sunset if this open at 100%
id: c1663eb4-3248-476e-9f48-be50b94e2e47
mode: single
trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 0.0
  - platform: state
    entity_id: binary_sensor.home
    from: 'off'
    to: 'on'
condition:
  - '{{ states.cover.bed.attributes.current_position | int > 80 }}'
  - condition: state
    entity_id: binary_sensor.home
    state: 'on'
  - condition: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 0.0
action:
  - service: notify.all_devices
    data:
      title: Jalousien
      message: "Sollen die Jalousien geschlossen werden?"
      data:
        actions:
          - action: CLOSE_BLINDS
            title: Schließen
