---
alias: Light Bedroom
id: 12b3c55f-75c6-4a6e-9db1-67a36d039a07
description: Turn on the light in the bedroom in the evening when we enter the room.
mode: restart
trigger:
  platform: state
  entity_id: binary_sensor.contact_bed_room
condition:
  condition: time
  after: '21:00:00'
  before: '01:00:00'
action:
  choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.contact_bed_room
        state: 'off'
      sequence:
        service: light.turn_off
        entity_id: light.go

  default:
    - service: light.turn_on
      entity_id: light.go
    - service: adaptive_lighting.apply
      entity_id: switch.adaptive_lighting_bed_go
