---
alias: NFC Bed
id: 32ed5830-426e-4135-bb5e-b15a43cb22e0
mode: single
trigger:
  - platform: tag
    tag_id: 32ed5830-426e-4135-bb5e-b15a43cb22e0
action:
  - action: activity_manager.update_activity
    data:
      now: true
      entity_id: sensor.haushalt_bettwasche_wechseln
  - action: notify.telegram_group
    data:
      message: 🛏 Das Bett wurde gewechselt
