---
alias: Fridge Temperature Way Too High
description: Notifies when the fridge temperature is way too high.
id: d4525926-bf63-44f6-a098-4a9475481b88
mode: single
variables:
  message: "❄️ Der Kühlschrank ist über 11°C!"
trigger:
  - platform: numeric_state
    entity_id: sensor.fridge_temperature
    above: 11
    for: "00:30:00"
action:
  - service: notify.telegram_group
    data:
      message: "{{ message }}"
  - service: notify.all_devices
    data:
      message: "{{ message }}"
