---
alias: Fridge Temperature
id: f4eff4f5-5699-4860-b455-f119b3927140
description: Notifies when the fridge is too hot or too cold
mode: restart
trigger:
  - platform: numeric_state
    entity_id: sensor.temperature_fridge
    id: "hot"
    above: 9
    for: "00:30:00"
  - platform: numeric_state
    entity_id: sensor.temperature_fridge
    id: "very_hot"
    above: 11
    for: "00:30:00"
  - platform: numeric_state
    entity_id: sensor.temperature_fridge
    id: "cold"
    below: 5
    for: "00:30:00"
action:
  choose:
  - conditions:
    - condition: trigger
      id: "very_hot"
    sequence:
      - action: notify.telegram_group
        data:
          message: ❄️ Der Kühlschrank ist über 11°C!
      - action: notify.apple_all
        data:
          message: ❄️ Der Kühlschrank ist über 11°C!
  - conditions:
      - condition: trigger
        id: "hot"
    sequence:
      - action: notify.telegram_group
        data:
          message: ❄️ Der Kühlschrank ist über 9°C!
  - conditions:
    - condition: trigger
      id: "cold"
    sequence:
      - action: notify.telegram_group
        data:
          message: ❄️ Der Kühlschrank ist unter 5°C!
