---
alias: Mi Kettle
id: 8efc42e9-6fe4-4134-93cb-10bd68862aee
description: Notifies when the smart kettle is done boiling the water.
mode: restart
trigger:
  platform: state
  entity_id: binary_sensor.ble_switch_wasserkocher
  from: 'on'
  to: 'off'
action:
  service: notify.mobile_app_iphone_13_pro
  data:
    message: Der Wasserkocher ist fertig
