---
alias: Turn off kitchen music
description: Turns off the music output in the kitchen when there is no more movement
id: 3d20240e-56b1-4ed2-9a9b-929017899472
mode: single
trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_human_presence
    to: 'off'
    for: '00:02:30'
action:
  - service: media_player.turn_off
    entity_id:
      - media_player.lms_kitchen
