---
alias: Light Kitchen
id: 0c2d7924-c4c3-4fd6-83de-b1f0d8a9c893
description: Turn on the light in the kitchen in the evening when presence is detected or turn it off if there is no motion.
mode: restart
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - binary_sensor.presence_kitchen
      - input_boolean.motion_sensor
      - alarm_control_panel.ha_alarm
      - media_player.kitchen_dot
action:
  choose:
    # Motion detected
    - conditions:
      - condition: state
        entity_id: binary_sensor.presence_kitchen
        state: 'on'
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: disarmed
      - condition: state
        entity_id: input_boolean.motion_sensor
        state: 'on'
      - condition: time
        before: "08:00:00"
        after: "19:00:00"
      - condition: or
        conditions:
        - condition: sun
          after: sunset
          after_offset: "-02:00:00"
        - condition: sun
          before: sunrise
          before_offset: "+01:00:00"
      sequence:
        - service: switch.turn_on
          entity_id: switch.circadian_lighting_kitchen
        - service: light.turn_on
          data:
            entity_id: light.kitchen_cabinets
            transition: 2
            kelvin: "{{ state_attr('sensor.circadian_values', 'colortemp') | int }}"
            brightness_pct: "{{ state_attr('switch.circadian_lighting_kitchen', 'brightness') | int }}"
    - conditions:
      # No more motion detected and music is not playing.
      - "{{ not is_state('media_player.kitchen_dot', 'playing') }}"
      sequence:
      - service: switch.turn_off
        entity_id: switch.circadian_lighting_kitchen
      - service: light.turn_off
        data:
          entity_id: light.kitchen_cabinets
          transition: 3
