---
alias: Light Kitchen
id: 0c2d7924-c4c3-4fd6-83de-b1f0d8a9c893
description: Turn on the light in the kitchen in the evening when presence is detected or turn it off if there is no motion.
mode: restart
trigger:
  - trigger: homeassistant
    event: start
  - trigger: event
    event_type: automation_reloaded
  - trigger: state
    entity_id:
      - binary_sensor.kitchen_human_presence
      - alarm_control_panel.ha_alarm
      - media_player.mass_kitchen
action:
  choose:
    # Motion detected
    - conditions:
      - condition: state
        entity_id: binary_sensor.kitchen_human_presence
        state: 'on'
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: disarmed
      - condition: or
        conditions:
        - condition: sun
          after: sunset
          after_offset: "-00:30:00"
        - condition: sun
          before: sunrise
          before_offset: "+00:30:00"
      sequence:
        - action: light.turn_on
          data:
            entity_id: light.kitchen_cabinets
    - conditions:
      # No more motion detected and music is not playing.
      - "{{ not is_state('media_player.mass_kitchen', 'playing')}}"

      sequence:
      - action: light.turn_off
        data:
          entity_id: light.kitchen_cabinets
          transition: 3
