---
alias: NFC Fridge
id: efea4cb0-c6ed-48ed-a3a5-d3a4d215a194
mode: single
trigger:
  - platform: tag
    tag_id: efea4cb0-c6ed-48ed-a3a5-d3a4d215a194
action:
  - service: activity_manager.update_activity
    data:
      now: true
      entity_id: sensor.haushalt_kuhlschrank_reinigen
  - service: notify.telegram_group
    data:
      message: ❄️ Der Kühlschrank wurde gereinigt
