---
alias: NFC Plants
id: 367aec8d-6aa6-4b25-a856-eb590f90627f
mode: single
trigger:
  - platform: tag
    tag_id: 367aec8d-6aa6-4b25-a856-eb590f90627f
action:
  - action: activity_manager.update_activity
    data:
      now: true
      entity_id: sensor.haushalt_pflanzen_giessen
  - action: notify.telegram_group
    data:
      message: "🪴 Die Pflanzen wurden gegossen."
