---
substitutions:
  name: BLE
  device: ble-bed
  mac: '0c:8b:95:a8:2b:60'

esphome:
  name: ${device}

esp32:
  board: m5stack-core-esp32

packages:
  main_base: !include common/main_base.yaml

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

# Required for SwitchBot
bluetooth_proxy:
  active: true
