---
substitutions:
  name: BLE
  device: ble-kitchen
  mac: '0c:dc:7e:63:62:d0'

esphome:
  name: ${device}

esp32:
  board: nodemcu-32s

packages:
  main_base: !include common/main_base.yaml

sensor:
  # XIAOMI MISCALE
  - platform: xiaomi_miscale
    mac_address: !secret mac_mi_scale
    weight:
      id: "miscale_weight"
      name: "Jannis Weight"
      icon: mdi:scale-bathroom
      accuracy_decimals: 2

  - platform: ble_client
    ble_client_id: oclean
    name: "Oclean Battery"
    service_uuid: '180f'
    characteristic_uuid: '2a19'
    icon: 'mdi:battery'
    unit_of_measurement: '%'
    type: characteristic

ble_client:
  mac_address: !secret mac_oclean
  id: oclean

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
