---
substitutions:
  device: light-kitchen-cabinets

packages:
  esphome_base: !include common/esphome_base.yaml
  main_base: !include common/main_base.yaml

# RGB Warm
output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w

light:
  - platform: rgbw
    name: "H801 Light"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    white: pwm_w
