---
substitutions:
  device: nspanel-living
  mac: '3c:e9:0e:85:d4:dc'
  panel_recv_topic: "tele/nspanel_living/RESULT"
  panel_send_topic: "cmnd/nspanel_living/CustomSend"

packages:
  main_base: !include common/main_base.yaml

<<: !include common/mqtt.yaml

logger:
  level: NONE

external_components:
  - source:
      type: git
      url: https://github.com/sairon/esphome-nspanel-lovelace-ui
      ref: release/v0.2.x
    components: [nspanel_lovelace]

esp32:
  board: esp32dev
  framework:
    type: arduino

nspanel_lovelace:
  id: nspanel
  mqtt_recv_topic: $panel_recv_topic
  mqtt_send_topic: $panel_send_topic

#bluetooth_proxy:

#esp32_ble_tracker:
#  id: ble_tracker
#  scan_parameters:
#    interval: 1100ms
#    window: 1100ms
#    active: false

binary_sensor:
  - platform: gpio
    name: $device Left Button
    internal: true
    pin:
      number: 14
      inverted: true
    on_click:
      - switch.toggle: relay_1
  - platform: gpio
    name: $device Right Button
    pin:
      number: 27
      inverted: true
    on_click:
      - mqtt.publish_json:
          topic: $panel_recv_topic
          payload: |-
            root["CustomRecv"] = "event,buttonPress2,navigate.cardGrid_avr,button";

sensor:
  - platform: wifi_signal
    name: $device WiFi Signal
    update_interval: 60s
    internal: true

  - platform: ntc
    id: temperature
    sensor: resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: $device Temperature

  - platform: resistance
    id: resistance_sensor
    sensor: ntc_source
    configuration: DOWNSTREAM
    resistor: 11.2kOhm
    internal: true

  - platform: adc
    id: ntc_source
    pin: 38
    update_interval: 10s
    attenuation: 11db
    internal: true

switch:
  - platform: gpio
    id: panel_power
    entity_category: config
    pin:
      number: 4
      inverted: true
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: $device Relay 1
    id: relay_1
    pin:
      number: 22
  - platform: gpio
    name: $device Relay 2
    id: relay_2
    pin:
      number: 19

output:
  - platform: ledc
    id: buzzer_out
    pin:
      number: 21

rtttl:
  id: buzzer
  output: buzzer_out

uart:
  - id: tf_uart
    tx_pin: 16
    rx_pin: 17
    baud_rate: 115200

api:
  services:
    - service: upload_tft
      variables:
        url: string
      then:
#id(ble_tracker).stop_scan();
        - lambda: |-
            id(nspanel).upload_tft(url);
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'
