---
substitutions:
  name: Soundsensor
  device: sound
  mac: '68:c6:3a:89:8c:e1'

esphome:
  name: ${device}
  platform: ESP8266
  board: nodemcuv2

packages:
  main_base: !include common/main_base.yaml

binary_sensor:
  - platform: gpio
    pin: D5
    name: "Sound level"
    filters:
      - delayed_off: 1s